export const baseUrl = 'http://192.168.128.2:8000'
// export const baseUrl = 'http://192.168.43.225:8000/'
export const loginUrl = '/api/auth/login/'
export const logoutUrl = '/api/auth/logout/'
export const registerUrl = '/api/auth/register/'
export const profileUrl = '/api/profile/'
export const eventsUrl = '/api/list_events/'
export const notifikasiUrl = '/api/notifikasi/'